[package]
name = "mstickerpicker"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0"
colored = "2.0"
html_color = "0.0"
once_cell = "1.13"
rocket = "0.5.0-rc.2"
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
rust-s3 = "0.31"
serde = "1.0"
