[package]
name = "mstickerpicker"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
axum = { version = "0.7.1", features = ["http2"] }
axum-extra = { version = "0.9.0", features = ["query"] }
dotenv = "0.15.0"
html_color = "0.0.0"
http = "1.0.0"
log = "0.4.20"
matrix-sdk = "0.7.1"
my-env-logger-style = "0.1.1"
serde = { version = "1.0.193", features = ["derive"] }
strum_macros = "0.25.3"
tokio = { version = "1.34.0", features = ["fs", "parking_lot", "macros", "rt-multi-thread"] }
yew = { version = "0.21.0", features = ["ssr"] }
