[package]
name = "mstickerpicker"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = "1.0"
actix-web = { version = "4.2.1", default-features = false, features = ["macros"] }
base64 = "0.13.1" # I do not like the new api above 20; wait for https://github.com/marshallpierce/rust-base64/issues/205#issuecomment-1346718136
colored = "2.0"
de_env = { version = "1.0.0", default-features = false }
dotenv = "0.15"
env_logger = { version = "0.10.0", default-features = false, features = ["color", "humantime", "auto-color"] }
futures-executor = "0.3"
futures-util = "0.3"
html_color = "0.0"
mstickereditor = { git = "https://github.com/LuckyTurtleDev/mstickereditor.git", branch = "lib" , default-features = false}
once_cell = "1.13"
rand = "0.8.5"
rust-s3 = {version = "0.32", features=["tokio-rustls-tls"], default-features=false}
serde = "1.0"
serde_json = "1"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "postgres", "offline"] }
tera = "1.17.1"
tokio = { version = "1.23.0", default-features = false, features = ["fs", "parking_lot"] }
log = "0.4.17"
thiserror = "1.0.38"
actix-web-lab = "0.18.8"
mstickerlib = { version = "0.1.0", default-features = false, features = ["log"] }
