[package]
name = "mstickerpicker"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
html_color = "0.0"
rocket = "0.5.0-rc.2"
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
serde = "1.0"
