name: Rust

on:
  push:
  pull_request:
  release:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mstickerpicker
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    steps:
      - run: sudo apt-get update -y && sudo apt-get install -y libavc1394-dev libavdevice-dev
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - name: install sqlx-cli
        uses: baptiste0928/cargo-install@v2.2
        with:
          crate: sqlx-cli
          version: "0.7"
      - uses: msrd0/install-rlottie-action@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo test --workspace --all-features
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/mstickerpicker
          RUST_BACKTRACE: 1
      # create sqlx-data.json to build dockerfile without running database
      - name: sqlx prepare
        run: cargo sqlx prepare --database-url "postgres://postgres:postgres@localhost/mstickerpicker"
      - uses: actions/upload-artifact@v3
        with:
          name: sqlx-data
          path: sqlx-data.json
          retention-days: 2


  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
