name: Docker

on:
  workflow_run:
    workflows: ["rust"]
    types: 
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: |
        image="ghcr.io/$GITHUB_REPOSITORY"
        tags=""
        tags+=" $GITHUB_SHA"
        tags+=" $GITHUB_REF_NAME"
        if [[ "$GITHUB_REF_TYPE" = tag ]]
        then
          tags+=" latest"
        fi
        tags_command=""
        while IFS= read -r tag
        do
          tags_command+=" --tag $image:$tag "
        done <<< tags
        docker login -u "$GITHUB_REPOSITORY_OWNER" -p "${{secrets.GITHUB_TOKEN}}" ghcr.io
        echo "build image with tags: $tags_command"
        docker buildx build ${push} --platform ${PLATFORMS:-linux/amd64} $tags_command .
